import Head from "next/head"
import SessionStateWrapper from "~/components/SessionStateWrapper"
import Button from "~/components/ui/Button"
import Layout from "~/components/ui/Layout"

export default function Home() {
    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <SessionStateWrapper
                Guest={(login) => (
                    <main className="min-h-screen flex flex-col items-center justify-center">
                        <Button onClick={login}>Login</Button>
                    </main>
                )}
                User={() => <Layout>siema</Layout>}
            />
        </>
    )
}
