import Head from "next/head"
import { useRouter } from "next/router"
import "react-calendar/dist/Calendar.css"
import DiariesListing from "~/components/DiariesListing"
import SessionStateWrapper from "~/components/SessionStateWrapper"
import StateWrapper from "~/components/StateWrapper"
import Button from "~/components/ui/Button"
import Layout from "~/components/ui/Layout"
import { api } from "~/utils/api"

export default function Home() {
    const diariesQuery = api.diary.getAll.useQuery()

    const router = useRouter()

    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <SessionStateWrapper
                Guest={(login) => (
                    <main className="min-h-screen flex flex-col items-center justify-center">
                        <Button onClick={login}>Login</Button>
                    </main>
                )}
                User={() => (
                    <Layout>
                        <StateWrapper
                            data={diariesQuery.data}
                            isLoading={diariesQuery.isLoading}
                            isError={diariesQuery.isError}
                            NonEmpty={(diaries) => (
                                <DiariesListing
                                    diaries={diaries}
                                    onClick={(diaryId) => {
                                        void router.push(`/diaries/${diaryId}`)
                                    }}
                                />
                            )}
                        />
                    </Layout>
                )}
            />
        </>
    )
}
